language: haskell
before_install:
  # Uncomment the next 3 lines whenever hackage is down.
  #  - mkdir -p ~/.cabal
  #  - cp config ~/.cabal/config
  #  - cabal update

  - cabal install --only-dependencies --enable-tests --force-reinstall
install:
  - cabal configure --enable-tests
  - cabal build
script:
  - cabal test --show-details=always
